# Generated by Django 4.0.1 on 2022-02-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contactt',
            new_name='Usercontact',
        ),
        migrations.AlterModelTable(
            name='usercontact',
            table='contactuser',
        ),
    ]
