# Generated by Django 4.0.1 on 2022-02-19 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.FileField(default='default.jpg', upload_to='product'),
        ),
    ]
