# Generated by Django 4.0.1 on 2022-02-19 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='image',
        ),
    ]
