# Generated by Django 4.0.1 on 2022-02-16 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('image', models.FileField(default='products.jpg', upload_to='product')),
            ],
        ),
    ]
